@endpoint=http://localhost:3000


###
POST {{ endpoint }}/login
Content-Type: application/json

{
  "email":"nicolas.dupon@mail.io",
  "password": "X346Dc5V7kfYmv!",
  "role" : "recruteur"
}

###
GET {{endpoint}}/scout/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicmVjcnV0ZXVyIiwiaWQiOjIsImZpcnN0bmFtZSI6Ik5pY29sYXMiLCJpYXQiOjE3MTMwMjI3MTIsImV4cCI6MTcxMzAyMjczMn0.rsz26_EsoFFjuXQgpimR5w6-LEcNgBZA8xEJ7ybftvI

###
GET {{ endpoint }}/player/1/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiam91ZXVyIiwiaWQiOjEsImZpcnN0bmFtZSI6IkplYW4iLCJpYXQiOjE3MTE2NTczMTQsImV4cCI6MTcxMTY1NzMzNH0.BK7YGZAuAw254W3fkZO0W8WelW7Ba_aDSx4mjkvkXcw

###
GET {{ endpoint }}/player/1/match/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiam91ZXVyIiwiaWQiOjEsImZpcnN0bmFtZSI6IkplYW4iLCJpYXQiOjE3MTE2NTc5NjksImV4cCI6MTcxMTY1Nzk4OX0.OBG0FwOZ2tK9r3IIpwxdFKsXr3heL-o9PLSg0y6xM-4
###
GET {{ endpoint }}/scout/search/?strong_foot=Gauche&position=Milieu offensif
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M

###

GET {{ endpoint }}/player/1/match
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiam91ZXVyIiwiaWQiOjEsImZpcnN0bmFtZSI6IkplYW4iLCJpYXQiOjE3MTE2NTY0MDIsImV4cCI6MTcxMTY1NjQyMn0.MnUT_4HYogS4gyqJpo0NrCUtHeihxt_XkbobDfmlHeI
###
GET {{ endpoint }}/scout/2/player/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjoxLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJEdWphcmRpbiIsImVtYWlsIjoiamVhbi5kdWphcmRpbkBtYWlsLmlvIiwiYmlydGhfZGF0ZSI6IjE5OTMtMDUtMjBUMjI6MDA6MDAuMDAwWiIsIm5hdGlvbmFsaXR5IjoiQnLDqXNpbGllbiIsImF2YXRhciI6IlNWRyIsImdlbnJlIjoiSG9tbWUiLCJoZWlnaHQiOjE4Mywid2VpZ2h0Ijo2Mywic3Ryb25nX2Zvb3QiOiJEcm9pdCIsInRlYW1faWQiOlsxLDZdLCJzY291dF9pZCI6WzEsMiwzLDVdLCJwb3NpdGlvbiI6IkF0dGFxdWFudCIsIm51bWJlcl9vZl9tYXRjaGVzX3BsYXllZCI6NTAsInJvbGUiOiJqb3VldXIiLCJpYXQiOjE3MDg2Nzk1ODIsImV4cCI6MTcwODY4MzE4Mn0.TSKTgbZh-vt5rcMc23tmCryqb0BiVNXqYfLr0L_cg54

###
GET {{endpoint}}/player/40/match/stats

GET {{ endpoint }}/scout/2/player/1/match/2/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M

###
GET {{ endpoint }}/scout/2/player/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M
###

GET {{endpoint}}/player/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M

GET {{endpoint}}/player/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjoxLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJEdWphcmRpbiIsImVtYWlsIjoiamVhbi5kdWphcmRpbkBtYWlsLmlvIiwiYmlydGhfZGF0ZSI6IjE5OTMtMDUtMjBUMjI6MDA6MDAuMDAwWiIsIm5hdGlvbmFsaXR5IjoiQnLDqXNpbGllbiIsImF2YXRhciI6IlNWRyIsImdlbnJlIjoiSG9tbWUiLCJoZWlnaHQiOjE4Mywid2VpZ2h0Ijo2Mywic3Ryb25nX2Zvb3QiOiJEcm9pdCIsInRlYW1faWQiOlsxLDZdLCJzY291dF9pZCI6WzEsMiwzLDVdLCJwb3NpdGlvbiI6IkF0dGFxdWFudCIsIm51bWJlcl9vZl9tYXRjaGVzX3BsYXllZCI6NTAsInJvbGUiOiJqb3VldXIiLCJpYXQiOjE3MDg1OTMwNDV9.aY8PGI7T3kbiQiUMXKhVqmNz85Z2D5g1zL8WeXybYtQ

###
POST {{ endpoint }}/register
Content-Type: application/json

{
  "firstname":"Romuald",
  "lastname":"Patfoort",
  "email":"rp@mail.io",
  "password": "Test123!", 
  "confirmedPassword": "Test123!", 
  "role": "joueur"
}


###
GET {{endpoint}}/scout/4/player/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M

###
GET {{endpoint}}/scout/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M
###
GET {{endpoint}}/player/1/match/1/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjoxLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJEdWphcmRpbiIsImVtYWlsIjoiamVhbi5kdWphcmRpbkBtYWlsLmlvIiwiYmlydGhfZGF0ZSI6IjE5OTMtMDUtMjBUMjI6MDA6MDAuMDAwWiIsIm5hdGlvbmFsaXR5IjoiQnLDqXNpbGllbiIsImF2YXRhciI6IlNWRyIsImdlbnJlIjoiSG9tbWUiLCJoZWlnaHQiOjE4Mywid2VpZ2h0Ijo2Mywic3Ryb25nX2Zvb3QiOiJEcm9pdCIsInRlYW1faWQiOlsxLDZdLCJzY291dF9pZCI6WzEsMiwzLDVdLCJwb3NpdGlvbiI6IkF0dGFxdWFudCIsIm51bWJlcl9vZl9tYXRjaGVzX3BsYXllZCI6NTAsInJvbGUiOiJqb3VldXIiLCJpYXQiOjE3MDg5MzcwNjIsImV4cCI6MTcwODk0MDY2Mn0.iSSLukEh13oReL6O35HUVjyqRIXxDM1v4FERU8gJ98Q


###
PATCH {{endpoint}}/player/1/match/2/stats
Content-Type: application/json

{
  "id": 21,
  "email": "rp@mail.io",
  "role": "joueur",
  "birth_date": "1990-06-12",
  "nationality": "Français",
  "genre": "Homme",
  "height": 184,
  "weight": 61,
  "strong_foot": "Droit",
  "position": "Attaquant"
}

###
POST {{ endpoint }}/register
Content-Type: application/json

{
  "firstname":"Romuald",
  "lastname":"Patfoort",
  "email":"rp@mail.io",
  "password": "Test123!", 
  "confirmedPassword": "Test123!", 
  "role": "joueur"
}

###
POST {{ endpoint }}/register/joueur
Content-Type: application/json

{
  "id": 21,
  "email": "rp@mail.io",
  "role": "joueur",
  "city": "St Ouen sur Seine",
  "club": "Red Star"
}


###
PATCH {{endpoint}}/scout/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjoxLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJEdWphcmRpbiIsImVtYWlsIjoiamVhbi5kdWphcmRpbkBtYWlsLmlvIiwiYmlydGhfZGF0ZSI6IjE5OTMtMDUtMjBUMjI6MDA6MDAuMDAwWiIsIm5hdGlvbmFsaXR5IjoiQnLDqXNpbGllbiIsImF2YXRhciI6IlNWRyIsImdlbnJlIjoiSG9tbWUiLCJoZWlnaHQiOjE4Mywid2VpZ2h0Ijo2Mywic3Ryb25nX2Zvb3QiOiJEcm9pdCIsInRlYW1faWQiOlsxLDZdLCJzY291dF9pZCI6WzEsMiwzLDVdLCJwb3NpdGlvbiI6IkF0dGFxdWFudCIsIm51bWJlcl9vZl9tYXRjaGVzX3BsYXllZCI6NTAsInJvbGUiOiJqb3VldXIiLCJpYXQiOjE3MDg5MzcwNjIsImV4cCI6MTcwODk0MDY2Mn0.iSSLukEh13oReL6O35HUVjyqRIXxDM1v4FERU8gJ98Q



{
  "firstname": "Jean Jacques",
  "lastname": "Dujardin"
}

###
POST {{endpoint}}/player/1/match
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjoxLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJEdWphcmRpbiIsImVtYWlsIjoiamVhbi5kdWphcmRpbkBtYWlsLmlvIiwiYmlydGhfZGF0ZSI6IjE5OTMtMDUtMjBUMjI6MDA6MDAuMDAwWiIsIm5hdGlvbmFsaXR5IjoiQnLDqXNpbGllbiIsImF2YXRhciI6IlNWRyIsImdlbnJlIjoiSG9tbWUiLCJoZWlnaHQiOjE4Mywid2VpZ2h0Ijo2Mywic3Ryb25nX2Zvb3QiOiJEcm9pdCIsInRlYW1faWQiOlsxLDZdLCJzY291dF9pZCI6WzEsMiwzLDVdLCJwb3NpdGlvbiI6IkF0dGFxdWFudCIsIm51bWJlcl9vZl9tYXRjaGVzX3BsYXllZCI6NTAsInJvbGUiOiJqb3VldXIiLCJpYXQiOjE3MDg5MzcwNjIsImV4cCI6MTcwODk0MDY2Mn0.iSSLukEh13oReL6O35HUVjyqRIXxDM1v4FERU8gJ98Q



{
  "homeTeam": 1,
  "awayTeam": 4,
  "date": "2024-02-22"
}


###
GET {{endpoint}}/player/1/match/3/stats



###
GET {{ endpoint }}/scout/2

###
DELETE {{ endpoint }}/scout/2/player/14


PATCH {{endpoint}}/player/1/match/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M
{
  "score": "10-10"
}


###
POST {{endpoint}}/player/1/match/1/stats
Authorization: Bearer Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjoxLCJmaXJzdG5hbWUiOiJKZWFuIiwibGFzdG5hbWUiOiJEdWphcmRpbiIsImVtYWlsIjoiamVhbi5kdWphcmRpbkBtYWlsLmlvIiwiYmlydGhfZGF0ZSI6IjE5OTMtMDUtMjBUMjI6MDA6MDAuMDAwWiIsIm5hdGlvbmFsaXR5IjoiQnLDqXNpbGllbiIsImF2YXRhciI6IlNWRyIsImdlbnJlIjoiSG9tbWUiLCJoZWlnaHQiOjE4Mywid2VpZ2h0Ijo2Mywic3Ryb25nX2Zvb3QiOiJEcm9pdCIsInRlYW1faWQiOlsxLDZdLCJzY291dF9pZCI6WzEsMiwzLDVdLCJwb3NpdGlvbiI6IkF0dGFxdWFudCIsIm51bWJlcl9vZl9tYXRjaGVzX3BsYXllZCI6NTAsInJvbGUiOiJqb3VldXIiLCJpYXQiOjE3MDg1OTMwNDV9.aY8PGI7T3kbiQiUMXKhVqmNz85Z2D5g1zL8WeXybYtQ

###
GET {{endpoint}}/datas/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M

###
PATCH {{endpoint}}/player/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGxheWVyX2lkIjozMywiZmlyc3RuYW1lIjoiSmVhbiIsImxhc3RuYW1lIjoiRHVqYXJkaW4iLCJlbWFpbCI6ImplYW4uZHVqYXJkaW5AbWFpbC5pbyIsImJpcnRoX2RhdGUiOiIxOTkzLTExLTI5VDIzOjAwOjAwLjAwMFoiLCJuYXRpb25hbGl0eSI6IlN1w6lkb2lzIiwiYXZhdGFyIjoiU1ZHIiwiZ2VucmUiOiJIb21tZSIsImhlaWdodCI6MTgzLCJ3ZWlnaHQiOjY3LCJzdHJvbmdfZm9vdCI6IkRyb2l0IiwidGVhbV9pZCI6W251bGxdLCJzY291dF9pZCI6W251bGxdLCJwb3NpdGlvbiI6IkdhcmRpZW4iLCJudW1iZXJfb2ZfbWF0Y2hlc19wbGF5ZWQiOjY2LCJyb2xlIjoiam91ZXVyIiwiaWF0IjoxNzA5MDIyNjQ4LCJleHAiOjE3MDkwMjYyNDh9.eLsEqWKmxkLrZCgGY6KDjW2yIaiNtAYRcxpwEfhUs8M
